### ISSUE TITLE
Add support for markdown files as templates

### ISSUE THREAD

**Issue by log101** [Ubn-Jr/LumosWeb#29]
I use markdown as my main markup language for notes and other documents. It'd awesome if you could add a support for markdown files, I'd like to use my markdown files as html pages. Maybe a simple converter like [PythonMarkdown](https://github.com/Python-Markdown/markdown)'s might help(see reference), thanks in advance!

reference: https://python-markdown.github.io/reference/#output_format

**Comment by Sddilora** [comment]
Thank you for the suggestion. I will look into adding support for markdown files and exploring options for converting them to HTML.
